export const MOCK_STATIONS = [
  // ---------- RED LINE (NW) ----------
  {
    id: "tuscany",
    name: "Tuscany Station",
    line: "Red",
    overallScore: 84,
    condition: "good",
    metrics: { cleanliness: 82, safety: 88, accessibility: 91, crowding: 76 },
    lastUpdated: "1 hour ago",
    imageUrl: "/station-placeholder.png",
  },
  {
    id: "crowfoot",
    name: "Crowfoot Station",
    line: "Red",
    overallScore: 80,
    condition: "good",
    metrics: { cleanliness: 78, safety: 82, accessibility: 89, crowding: 74 },
    lastUpdated: "2 hours ago",
    imageUrl: "/station-placeholder.png",
  },
  {
    id: "dalhousie",
    name: "Dalhousie Station",
    line: "Red",
    overallScore: 76,
    condition: "moderate",
    metrics: { cleanliness: 75, safety: 73, accessibility: 87, crowding: 70 },
    lastUpdated: "3 hours ago",
    imageUrl: "/station-placeholder.png",
  },
  {
    id: "brentwood",
    name: "Brentwood Station",
    line: "Red",
    overallScore: 85,
    condition: "good",
    metrics: { cleanliness: 82, safety: 86, accessibility: 90, crowding: 74 },
    lastUpdated: "2 hours ago",
    imageUrl: "/station-placeholder.png",
  },
  {
    id: "university",
    name: "University Station",
    line: "Red",
    overallScore: 79,
    condition: "moderate",
    metrics: { cleanliness: 77, safety: 81, accessibility: 93, crowding: 72 },
    lastUpdated: "1 hour ago",
    imageUrl: "/station-placeholder.png",
  },
  {
    id: "banff-trail",
    name: "Banff Trail Station",
    line: "Red",
    overallScore: 73,
    condition: "moderate",
    metrics: { cleanliness: 70, safety: 75, accessibility: 85, crowding: 68 },
    lastUpdated: "4 hours ago",
    imageUrl: "/station-placeholder.png",
  },
  {
    id: "lions-park",
    name: "Lions Park Station",
    line: "Red",
    overallScore: 72,
    condition: "moderate",
    metrics: { cleanliness: 69, safety: 71, accessibility: 83, crowding: 66 },
    lastUpdated: "5 hours ago",
    imageUrl: "/station-placeholder.png",
  },
  {
    id: "sait",
    name: "SAIT / AUArts / Jubilee Station",
    line: "Red",
    overallScore: 81,
    condition: "good",
    metrics: { cleanliness: 79, safety: 83, accessibility: 90, crowding: 77 },
    lastUpdated: "2 hours ago",
    imageUrl: "/station-placeholder.png",
  },
  {
    id: "sunnyside",
    name: "Sunnyside Station",
    line: "Red",
    overallScore: 77,
    condition: "moderate",
    metrics: { cleanliness: 74, safety: 78, accessibility: 88, crowding: 71 },
    lastUpdated: "3 hours ago",
    imageUrl: "/station-placeholder.png",
  },

  // ---------- DOWNTOWN (DUAL LINE) ----------
  {
    id: "8-street-sw",
    name: "8 Street SW Station",
    line: "Dual",
    overallScore: 83,
    condition: "good",
    metrics: { cleanliness: 80, safety: 85, accessibility: 92, crowding: 78 },
    lastUpdated: "30 min ago",
    imageUrl: "/station-placeholder.png",
  },
  {
    id: "city-hall",
    name: "City Hall / Bow Valley College Station",
    line: "Dual",
    overallScore: 82,
    condition: "good",
    metrics: { cleanliness: 80, safety: 81, accessibility: 92, crowding: 75 },
    lastUpdated: "45 min ago",
    imageUrl: "/station-placeholder.png",
  },

  // ---------- RED LINE (SOUTH) ----------
  {
    id: "chinook",
    name: "Chinook Station",
    line: "Red",
    overallScore: 74,
    condition: "moderate",
    metrics: { cleanliness: 72, safety: 70, accessibility: 86, crowding: 68 },
    lastUpdated: "1 day ago",
    imageUrl: "/station-placeholder.png",
  },
  {
    id: "heritage",
    name: "Heritage Station",
    line: "Red",
    overallScore: 71,
    condition: "moderate",
    metrics: { cleanliness: 69, safety: 73, accessibility: 85, crowding: 67 },
    lastUpdated: "6 hours ago",
    imageUrl: "/station-placeholder.png",
  },
  {
    id: "anderson",
    name: "Anderson Station",
    line: "Red",
    overallScore: 75,
    condition: "moderate",
    metrics: { cleanliness: 73, safety: 78, accessibility: 87, crowding: 70 },
    lastUpdated: "4 hours ago",
    imageUrl: "/station-placeholder.png",
  },
  {
    id: "somerset-bridlewood",
    name: "Somerset–Bridlewood Station",
    line: "Red",
    overallScore: 78,
    condition: "moderate",
    metrics: { cleanliness: 76, safety: 80, accessibility: 88, crowding: 72 },
    lastUpdated: "3 hours ago",
    imageUrl: "/station-placeholder.png",
  },

  // ---------- BLUE LINE ----------
  {
    id: "69-street",
    name: "69 Street Station",
    line: "Blue",
    overallScore: 86,
    condition: "good",
    metrics: { cleanliness: 84, safety: 89, accessibility: 93, crowding: 79 },
    lastUpdated: "1 hour ago",
    imageUrl: "/station-placeholder.png",
  },
  {
    id: "westbrook",
    name: "Westbrook Station",
    line: "Blue",
    overallScore: 73,
    condition: "moderate",
    metrics: { cleanliness: 71, safety: 75, accessibility: 86, crowding: 68 },
    lastUpdated: "2 hours ago",
    imageUrl: "/station-placeholder.png",
  },
  {
    id: "zoo",
    name: "Zoo Station",
    line: "Blue",
    overallScore: 70,
    condition: "moderate",
    metrics: { cleanliness: 67, safety: 72, accessibility: 84, crowding: 65 },
    lastUpdated: "5 hours ago",
    imageUrl: "/station-placeholder.png",
  },
  {
    id: "whitehorn",
    name: "Whitehorn Station",
    line: "Blue",
    overallScore: 68,
    condition: "moderate",
    metrics: { cleanliness: 65, safety: 69, accessibility: 83, crowding: 63 },
    lastUpdated: "6 hours ago",
    imageUrl: "/station-placeholder.png",
  },
  {
    id: "saddletowne",
    name: "Saddletowne Station",
    line: "Blue",
    overallScore: 61,
    condition: "poor",
    metrics: { cleanliness: 58, safety: 55, accessibility: 79, crowding: 63 },
    lastUpdated: "3 hours ago",
    imageUrl: "/station-placeholder.png",
  },
];