export const MOCK_FEEDBACK = [
  {
    id: "f1",
    user: "Anonymous",
    station: "Brentwood",
    line: "Red",
    feedback: "Very clean station, but gets packed after 5pm.",
    categoryRatings: {
      cleanliness: 88,
      safety: 82,
      accessibility: 90,
      crowding: 73,
    },
    status: "needs_review",
    submitted: "2 days ago",
  },
  {
    id: "f2",
    user: "CalgaryCommuter",
    station: "City Hall",
    line: "Dual",
    feedback: "Could use more security presence during late hours.",
    categoryRatings: {
      cleanliness: 72,
      safety: 60,
      accessibility: 85,
      crowding: 78,
    },
    status: "needs_review",
    submitted: "6 hours ago",
  },
  {
    id: "f3",
    user: "Anonymous",
    station: "Marlborough",
    line: "Blue",
    feedback: "Saw some concerning behavior on the platform last night.",
    categoryRatings: {
      cleanliness: 65,
      safety: 55,
      accessibility: 82,
      crowding: 70,
    },
    status: "needs_review",
    submitted: "1 hour ago",
  },
  {
    id: "f4",
    user: "YYCTransitLover",
    station: "Dalhousie",
    line: "Red",
    feedback: "Always feels safe, even in the evening.",
    categoryRatings: {
      cleanliness: 92,
      safety: 90,
      accessibility: 88,
      crowding: 75,
    },
    status: "needs_review",
    submitted: "5 days ago",
  },
  {
    id: "f5",
    user: "Anonymous",
    station: "Chinook",
    line: "Red",
    feedback: "Parking chaos, but the station itself is great.",
    categoryRatings: {
      cleanliness: 86,
      safety: 80,
      accessibility: 89,
      crowding: 65,
    },
    status: "needs_review",
    submitted: "3 days ago",
  },
  {
    id: "f6",
    user: "LRTDaily",
    station: "Bridgeland/Memorial",
    line: "Blue",
    feedback: "Area feels sketchy late at night.",
    categoryRatings: {
      cleanliness: 70,
      safety: 58,
      accessibility: 87,
      crowding: 72,
    },
    status: "needs_review",
    submitted: "2 days ago",
  },
  {
    id: "f7",
    user: "TransitRider88",
    station: "Tuscany",
    line: "Red",
    feedback: "Escalators were working today which is nice.",
    categoryRatings: {
      cleanliness: 4,
      safety: 5,
      accessibility: 4,
      crowding: 3
    },
    status: "approved",
    submitted: "2 hours ago",
  },
  {
    id: "f8",
    user: "Anonymous",
    station: "Franklin",
    line: "Blue",
    feedback: "Platform was pretty quiet this morning.",
    categoryRatings: {
      cleanliness: 3,
      safety: 4,
      accessibility: 3,
      crowding: 2
    },
    status: "approved",
    submitted: "5 hours ago",
  },
  {
    id: "f9",
    user: "YYCUser",
    station: "Sunnyside",
    line: "Red",
    feedback: "Trains were on time during my commute.",
    categoryRatings: {
      cleanliness: 4,
      safety: 5,
      accessibility: 4,
      crowding: 3
    },
    status: "approved",
    submitted: "1 day ago",  
  },
  {
    id: "f10",
    user: "CalgaryCommuter",
    station: "39 Avenue",
    line: "Red",
    feedback: "Lighting seems brighter than before",
    categoryRatings: {
      cleanliness: 4,
      safety: 5,
      accessibility: 4,
      crowding: 3
    },
    status: "approved",
    submitted: "3 days ago",  
  },
  {
    id: "f11",
    user: "Anonymous",
    station: "Whitehorn",
    line: "Blue",
    feedback: "asdasfjldsksdf",
    categoryRatings: {
      cleanliness: 3,
      safety: 4,
      accessibility: 3,
      crowding: 2
    },
    status: "rejected",
    submitted: "1 hour ago",
  },
  {
    id: "f12",
    user: "TrainFan123",
    station: "Brentwood",
    line: "Red",
    feedback: "lol idk just testing this",
    categoryRatings: {
      cleanliness: 3,
      safety: 4,
      accessibility: 3,
      crowding: 2
    },
    status: "rejected",
    submitted: "2 days ago",
  },
  {
    id: "f13",
    user: "Anonymous",
    station: "Rundle",
    line: "Blue",
    feedback: ".",
    categoryRatings: {
      cleanliness: 3,
      safety: 4,
      accessibility: 3,
      crowding: 2
    },
    status: "rejected",
    submitted: "4 days ago",  
  },
  {
    id: "f14",
    user: "YYCTransitKid",
    station: "Chinook",
    line: "Red",
    feedback: "This app is stupid",
    categoryRatings: {
      cleanliness: 3,
      safety: 4,
      accessibility: 3,
      crowding: 2
    },
    submitted: "6 days ago",  
    status: "rejected",
  },
]

export const MOCK_STATION_OPTIONS = [
  "Brentwood",
  "City Hall",
  "Marlborough",
  "Dalhousie",
  "Chinook",
  "Bridgeland/Memorial",
  "Tuscany",
  "Franklin",
  "Sunnyside",
  "39 Avenue",
  "Whitehorn",
  "Rundle",
];